version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: rr-postgres
    restart: always
    environment:
      POSTGRES_DB: realtimeracing
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: